# Generated by Django 5.0.14 on 2026-05-04 19:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('nome_area', models.CharField(max_length=255, verbose_name='Nome da Área')),
                ('atuacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Atuação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem_branco', models.TextField(blank=True, null=True, verbose_name='Imagem (Branco)')),
                ('imagem_escuro', models.TextField(blank=True, null=True, verbose_name='Imagem (Escuro)')),
                ('pgi_evolucao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Evolução PGI')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo', models.CharField(max_length=255, verbose_name='Eixo')),
                ('evolucao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Evolução')),
                ('imagem', models.TextField(blank=True, null=True, verbose_name='Imagem')),
                ('imagem_branco', models.TextField(blank=True, null=True, verbose_name='Imagem (Branco)')),
                ('imagem_escuro', models.TextField(blank=True, null=True, verbose_name='Imagem (Escuro)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Eixo',
                'verbose_name_plural': 'Eixos',
                'db_table': 'pgi_eixos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('gestor_chefe', models.BooleanField(default=False, verbose_name='Gestor Chefe')),
                ('suporte_admin', models.BooleanField(default=False, verbose_name='Suporte Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcaoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField(verbose_name='Ação')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('ordem', models.IntegerField(blank=True, null=True, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsavel', to=settings.AUTH_USER_MODEL)),
                ('responsavel_suplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_suplan', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='pgi.area')),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='pgi.eixo')),
            ],
            options={
                'verbose_name': 'Ação Institucional',
                'verbose_name_plural': 'Ações Institucionais',
                'db_table': 'pgi_acao_institucional',
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Atualização')),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Anterior')),
                ('valor_evolucao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Evolução')),
                ('ultima_atualiz_percentual', models.BooleanField(default=False, verbose_name='Última Atualização Percentual')),
                ('atualizacao_percentual', models.BooleanField(default=False, verbose_name='Atualização Percentual')),
                ('tipo_entrega_marco', models.BooleanField(default=False, verbose_name='Tipo Entrega Marco')),
                ('progresso_entrega', models.TextField(blank=True, null=True, verbose_name='Progresso da Entrega')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='pgi.acaoinstitucional')),
                ('responsavel_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizacoes_acoes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atualização da Ação',
                'verbose_name_plural': 'Atualizações das Ações',
                'db_table': 'pgi_atualizacao_acao',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.TextField(verbose_name='Etapa')),
                ('etapa_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Etapa Referência')),
                ('ordem', models.IntegerField(blank=True, null=True, verbose_name='Ordem')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('bl_deletado', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='pgi.acaoinstitucional')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'pgi_etapas',
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Atualização')),
                ('progresso_entrega', models.TextField(verbose_name='Progresso da Entrega')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('bl_deletado', models.BooleanField(default=False, verbose_name='Deletado')),
                ('responsavel_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizacoes_etapas_registradas', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='pgi.etapa')),
            ],
            options={
                'verbose_name': 'Atualização da Etapa',
                'verbose_name_plural': 'Atualizações das Etapas',
                'db_table': 'atualizacao_etapa',
            },
        ),
        migrations.CreateModel(
            name='UserAssessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulares_assessorados', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessores_do_titular', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessor de Usuário',
                'verbose_name_plural': 'Assessores de Usuários',
                'db_table': 'user_assessores',
            },
        ),
    ]
