# Generated by Django 5.0.14 on 2026-05-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='area',
            name='imagem_branco',
        ),
        migrations.RemoveField(
            model_name='area',
            name='imagem_escuro',
        ),
        migrations.AlterField(
            model_name='area',
            name='atuacao',
            field=models.BooleanField(choices=[(True, 'Área Fim'), (False, 'Área Meio')], default=False, verbose_name='Atuação (Fim / Meio)'),
        ),
        migrations.AlterField(
            model_name='area',
            name='pgi_evolucao',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Evolução PGI'),
        ),
    ]
