# Generated by Django 5.0.14 on 2026-06-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi', '0002_remove_area_descricao_remove_area_imagem_branco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gestor_chefe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suporte_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='pgi.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gestor', 'Gestor'), ('editor', 'Editor'), ('leitor', 'Leitor')], default='leitor', max_length=10, verbose_name='Perfil'),
        ),
        migrations.DeleteModel(
            name='UserAssessor',
        ),
    ]
